services:
  - type: pserv
    name: mysql
    plan: standard
    env: docker
    autoDeploy: false
    disk:
      name: mysql
      mountPath: /var/lib/mysql
      sizeMB: 300
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: MYSQL_DATABASE
        value: mydatabase
      - key: MYSQL_USER
        value: myuser
      - key: MYSQL_PASSWORD
        generateValue: true

